### ISSUE TITLE
No IP in Networking, even though XC reports version 6.2 installed

### ISSUE THREAD

**Issue by simoninkin** [xen-tools/xen-tools#43]
Hi,

Please help me understand what might be wrong with my system?
When I boot a CoreOS ISO image directly, the provided cloud-config installs a systemd unit that runs the XenTools agent. When booting ISO directly, the XC reports 'Virtualization state: Optimized (version 6.2 installed)', I see the IP in the Networking tab and everyone's happy.

However, when I boot my CoreOS from a iPXE script, the provided systemd unit shows no errors in the log, shows that it has started up, XC reports the same 'Virtualization state: Optimized (version 6.2 installed)' message, but now I don't get the IP in the Networking tab! I can get it from within the VM with ifconfig, but I don't see it in XenCenter. This prevents me from enabling XenServer Docker management for the VM. Also, the agent seems to be in a hanged state, because upon VM restart it prevents the machich from being restart and a timeout has to finish to forecefully kill the service and reboot. One more thing - I could swear this used to work! Before preparing all the iPXE chains and other stuff I made sure it worked when booted via iPXE.

journalctl log (after a few reboots):

> -- Logs begin at Thu 2016-09-08 09:01:51 UTC, end at Thu 2016-09-08 13:41:23 UTC. --
Sep 08 09:02:01 simoncgcoreos1 systemd[1]: Starting Hypervisor Linux Guest Agent...
Sep 08 09:02:01 simoncgcoreos1 systemd[1]: Started Hypervisor Linux Guest Agent.
Sep 08 11:54:34 simoncgcoreos1 systemd[1]: Stopping Hypervisor Linux Guest Agent...
Sep 08 11:56:04 simoncgcoreos1 systemd[1]: xe-linux-distribution.service: State 'stop-sigterm' timed out. Killing.
Sep 08 11:56:04 simoncgcoreos1 systemd[1]: xe-linux-distribution.service: Main process exited, code=killed, status=9/KILL
Sep 08 11:56:04 simoncgcoreos1 systemd[1]: Stopped Hypervisor Linux Guest Agent.
Sep 08 11:56:04 simoncgcoreos1 systemd[1]: xe-linux-distribution.service: Unit entered failed state.
Sep 08 11:56:04 simoncgcoreos1 systemd[1]: xe-linux-distribution.service: Failed with result 'signal'.
Sep 08 11:56:04 simoncgcoreos1 systemd[1]: Starting Hypervisor Linux Guest Agent...
Sep 08 11:56:04 simoncgcoreos1 systemd[1]: Started Hypervisor Linux Guest Agent.
Sep 08 12:56:37 simoncgcoreos1 systemd[1]: Stopping Hypervisor Linux Guest Agent...
Sep 08 12:58:08 simoncgcoreos1 systemd[1]: xe-linux-distribution.service: State 'stop-sigterm' timed out. Killing.
Sep 08 12:58:08 simoncgcoreos1 systemd[1]: xe-linux-distribution.service: Main process exited, code=killed, status=9/KILL
Sep 08 12:58:08 simoncgcoreos1 systemd[1]: Stopped Hypervisor Linux Guest Agent.
Sep 08 12:58:08 simoncgcoreos1 systemd[1]: xe-linux-distribution.service: Unit entered failed state.
Sep 08 12:58:08 simoncgcoreos1 systemd[1]: xe-linux-distribution.service: Failed with result 'signal'.
-- Reboot --
Sep 08 13:16:11 simoncgcoreos1 systemd[1]: Starting Hypervisor Linux Guest Agent...
Sep 08 13:16:11 simoncgcoreos1 systemd[1]: Started Hypervisor Linux Guest Agent.
-- Reboot --
Sep 08 13:20:21 simoncgcoreos1 systemd[1]: Stopped Hypervisor Linux Guest Agent.
-- Reboot --
Sep 08 13:23:44 simoncgcoreos1 systemd[1]: Stopped Hypervisor Linux Guest Agent.
Sep 08 13:24:06 simoncgcoreos1 systemd[1]: Starting Hypervisor Linux Guest Agent...
Sep 08 13:24:06 simoncgcoreos1 systemd[1]: Started Hypervisor Linux Guest Agent.

What has happened? How do I debug this?

Thanks,
Simon

**Comment by xtaran** [comment]
Hi,

I think you mix up Citrix's [__XenServer Tools__](http://docs.citrix.com/en-us/xencenter/6-1/xs-xc-vms-configuring/xs-xc-vms-installtools.html) with [__xen-tools__](https://xen-tools.org/) as I see no trace of __xen-tools__ in your issue.

__xen-tools__ is a _third-party_ open source commandline toolset to _provision_ DomUs in an automated fashion and is not originating at Citrix.

**Comment by simoninkin** [comment]
Oops =) yeah, these are XenServer tools. Just a mix up with similar names. I thought this was Citrix's repo. (I thought it was strange Citrix not being the maintainer) oh well. Sorry about this inconvenience.

**Comment by xtaran** [comment]
You're not the first one. :-) But as far as I know, "xen-tools" is the older "product", at least it exists longer than Xen belongs to Citrix.

**Comment by xtaran** [comment]
Citrix seems to have an organizational account on Github, too: https://github.com/citrix -- maybe there's an according repository, too.

**Comment by simoninkin** [comment]
Thanks for the info, I'll have a look!

**Comment by simoninkin** [comment]
To the lonely stranger who finds this,
There is apparently an issue with CoreOS's latest build. The bug has been reported:
https://github.com/coreos/bugs/issues/1563
https://bugs.xenserver.org/browse/XSO-612
