### ISSUE TITLE
Debian buster openssh-server broken setup

### ISSUE THREAD

**Issue by zxzharmlesszxz** [xen-tools/xen-tools#59]
At debootstrap stage:
```
mkstemps: No such file or directory
dpkg: error processing package openssh-server (--configure):
 installed openssh-server package post-installation script subprocess returned error exit status 1
Processing triggers for systemd (241-5) ...
Processing triggers for libc-bin (2.28-10) ...
Errors were encountered while processing:
 openssh-server
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
and after start guests - can't access via ssh because package not completely installed
when trying manualy setup package - configuration dialog displayed

**Comment by xtaran** [comment]
Any details on what the configuration dialog displayed?

**Comment by zxzharmlesszxz** [comment]
This dialog displayed when I changed sshd_config file by role
But I try to disable role and setup base guest buster distribution:
at the log
`Setting up openssh-server (1:7.9p1-10) ...
mkstemps: No such file or directory
dpkg: error processing package openssh-server (--configure):
 installed openssh-server package post-installation script subprocess returned error exit status 1
Setting up libklibc:amd64 (2.0.6-1) ...
Setting up klibc-utils (2.0.6-1) ...
No diversion 'diversion of /usr/share/initramfs-tools/hooks/klibc to /usr/share/initramfs-tools/hooks/klibc^i-t by klibc-utils', none removed.
Setting up initramfs-tools-core (0.133) ...
Setting up initramfs-tools (0.133) ...
update-initramfs: deferring update (trigger activated)
Processing triggers for initramfs-tools (0.133) ...
Errors were encountered while processing:
 openssh-server
E: Sub-process /usr/bin/dpkg returned an error code (1)
`
at the guest openssh-server package not completely installed
after running manualy 'apt-get install -y openssh-server' - all work fine,
but this is not true way, because I want to connect via ssh to vm

**Comment by xtaran** [comment]
Hmm, ok, so `mkstemps: No such file or directory` might be the cause. Sounds as if something in the chroot setup changed since I tested it last time shortly before the freeze for buster. Will need to have a closer look at it.

**Comment by zxzharmlesszxz** [comment]
> Any details on what the configuration dialog displayed?
I try to fix it by adding finalrole=sshd with contents
`#!/bin/sh

prefix=$1

if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi

logMessage Script $0 starting
chroot ${prefix} sh -c 'DEBIAN_FRONTEND=noninteractive TMPDIR=/tmp apt-get install -f -y -qq'
installDebianPackageAndRecommends ${prefix} openssh-server
logMessage Script $0 finished
`
and this fixed this issue

**Comment by xtaran** [comment]
Does it make a difference if you don't define `TMPDIR`? If not, that might be missing.

**Comment by zxzharmlesszxz** [comment]
> Does it make a difference if you don't define `TMPDIR`? If not, that might be missing.

Without this var I got the error `mkstemps: No such file or directory`

**Comment by xtaran** [comment]
Ok, thanks. Will dig into that direction...
